const dummyJobs = [
  {
    title: "Salesforce Administrator",
    company: "Goodway Group",
    location: "Dubai",
    country: "UAE",
    city: "Dubai",
    domain: "CRM",
    experience: "Experienced",
    time: "10 hours ago",
    tags: ["CRM", "Salesforce", "Communication"],
  },
  {
    title: "Mindset Coach",
    company: "Living Portably",
    location: "Abu Dhabi",
    country: "UAE",
    city: "Abu Dhabi",
    domain: "Education",
    experience: "Fresher",
    time: "2 days ago",
    tags: ["Training", "Soft Skills"],
  },
  {
    title: "Software Developer",
    company: "Tech Innovations",
    location: "Berlin",
    country: "Germany",
    city: "Berlin",
    domain: "IT",
    experience: "Experienced",
    time: "1 day ago",
    tags: ["JavaScript", "React"],
  },
  {
    title: "Marketing Executive",
    company: "Maple Growth",
    location: "Toronto",
    country: "Canada",
    city: "Toronto",
    domain: "Marketing",
    experience: "Fresher",
    time: "3 days ago",
    tags: ["SEO", "Campaigns"],
  },
  {
    title: "Business Analyst",
    company: "LuxTech",
    location: "Luxembourg City",
    country: "Luxembourg",
    city: "Luxembourg City",
    domain: "Business",
    experience: "Experienced",
    time: "1 day ago",
    tags: ["Analytics", "Strategy"],
  },
  {
    title: "Finance Assistant",
    company: "GreenBank",
    location: "London",
    country: "UK",
    city: "London",
    domain: "Finance",
    experience: "Fresher",
    time: "1 day ago",
    tags: ["Accounts", "Excel"],
  },
  {
    title: "Nurse Assistant",
    company: "Care Health",
    location: "Dublin",
    country: "Ireland",
    city: "Dublin",
    domain: "Healthcare",
    experience: "Experienced",
    time: "5 hours ago",
    tags: ["Nursing", "Patient Care"],
  },
  {
    title: "Product Designer",
    company: "TechHub",
    location: "Singapore",
    country: "Singapore",
    city: "Singapore",
    domain: "Design",
    experience: "Fresher",
    time: "Today",
    tags: ["UI", "Figma", "Prototyping"],
  },
  {
    title: "IT Technician",
    company: "NextTech",
    location: "Kuala Lumpur",
    country: "Malaysia",
    city: "Kuala Lumpur",
    domain: "IT",
    experience: "Experienced",
    time: "3 days ago",
    tags: ["Hardware", "Networking"],
  },
  {
    title: "HR Intern",
    company: "Aussie Works",
    location: "Melbourne",
    country: "Australia",
    city: "Melbourne",
    domain: "HR",
    experience: "Fresher",
    time: "2 days ago",
    tags: ["Recruitment", "Admin"],
  },
  {
    title: "Sales Lead",
    company: "SA Global",
    location: "Cape Town",
    country: "South Africa",
    city: "Cape Town",
    domain: "Sales",
    experience: "Experienced",
    time: "4 days ago",
    tags: ["B2B", "Cold Calling"],
  },
  {
    title: "Mechanical Engineer",
    company: "DenTech",
    location: "Copenhagen",
    country: "Denmark",
    city: "Copenhagen",
    domain: "Engineering",
    experience: "Experienced",
    time: "1 day ago",
    tags: ["CAD", "Manufacturing"],
  },
];

export default dummyJobs;
