const uaeDubaiJobs = [
  {
    title: "Senior Software Engineer (RDMA)",
    company: "GGateway for Outsourcing IT",
    location: "Dubai",
    country: "UAE",
    city: "Dubai",
    domain: "Semiconductor",
    experience: "Senior",
    minExperience: 5,
    time: "Recent",
    tags: ["Python", "Linux", "RDMA", "Networking", "Performance Tuning"],
    salary: "$3,000 - $4,000",
    type: "Full–time",
    level: "Management",
  },
  {
    title: "AI Software Development Manager",
    company: "Alsadd trading and contracting",
    location: "Dubai",
    country: "UAE",
    city: "Dubai",
    domain: "AI",
    experience: "Director/Head",
    minExperience: 7,
    time: "Recent",
    tags: ["AI", "Leadership", "Startup", "Team Building"],
    type: "Full–time",
  },
  {
    title: "Java Developer",
    company: "Harjai Computers",
    location: "Dubai",
    country: "UAE",
    city: "Dubai",
    domain: "IT",
    experience: "Mid career",
    minExperience: 3,
    time: "Recent",
    tags: ["Java", "REST API", "Problem Solving", "Database"],
    type: "Full–time",
  },
  {
    title: "Senior Accounting Manager",
    company: "Biotech Pharma",
    location: "Dubai",
    country: "UAE",
    city: "Dubai",
    domain: "Finance",
    experience: "Mid career",
    minExperience: 4,
    time: "Recent",
    tags: ["Accounting", "VAT", "IFRS", "Compliance"],
    salary: "$5,000 - $6,000",
    type: "Full–time",
  },
  {
    title: "Admin Assistant",
    company: "Maggadit",
    location: "Dubai",
    country: "UAE",
    city: "Dubai",
    domain: "Administration",
    experience: "Mid career",
    minExperience: 2,
    time: "Recent",
    tags: ["Office Management", "Scheduling", "Communication"],
    salary: "$5,000 - $6,000",
    type: "Full–time",
  },
  {
    title: "Receptionist",
    company: "Cure Wibe",
    location: "Dubai",
    country: "UAE",
    city: "Dubai",
    domain: "Front Office",
    experience: "Entry level",
    minExperience: 2,
    time: "Recent",
    tags: ["Customer Service", "Clerical", "Greeting Visitors"],
    type: "Full–time",
  },
  {
    title: "Junior Accountant for Cash & LPO responsibilities",
    company: "Confidential Company",
    location: "Dubai",
    country: "UAE",
    city: "Dubai",
    domain: "Finance",
    experience: "Entry level",
    minExperience: 1,
    time: "Recent",
    tags: ["Cash Flow", "LPO", "Accounting"],
    salary: "$500 - $1,000",
    type: "Full–time",
  },
  {
    title: "Credit Controller",
    company: "Confidential Company",
    location: "Dubai",
    country: "UAE",
    city: "Dubai",
    domain: "Finance",
    experience: "Management",
    minExperience: 5,
    time: "Recent",
    tags: ["Credit Management", "Collections", "Accounting Software"],
    salary: "$3,000 - $4,000",
    type: "Full–time",
  },
];

const londonJobs = [
  {
    title: "Indian Ocean Luxury Travel Consultant",
    company: "Best At Travel",
    location: "London",
    country: "UK",
    city: "London",
    domain: "Travel",
    experience: "Mid career",
    minExperience: 3,
    time: "Recent",
    tags: ["Luxury Travel", "Sales", "Indian Ocean", "Customer Service"],
    type: "Full–time",
  },
  {
    title: "Television Presenter",
    company: "Vaibhav Global",
    location: "London",
    country: "UK",
    city: "London",
    domain: "Media",
    experience: "Experienced",
    minExperience: 5,
    time: "Recent",
    tags: ["Presenting", "Fashion", "Jewelry", "Broadcast"],
    type: "Full–time",
  },
  {
    title: "Digital Marketing Intern",
    company: "Roseberys",
    location: "London SE27",
    country: "UK",
    city: "London",
    domain: "Marketing",
    experience: "Internship",
    minExperience: 0,
    time: "Recent",
    tags: ["Marketing", "Data Analytics", "Intern", "SEO"],
    type: "Internship",
  },
  {
    title: "Investment Analyst",
    company: "PICTET",
    location: "London",
    country: "UK",
    city: "London",
    domain: "Finance",
    experience: "Mid career",
    minExperience: 3,
    time: "Recent",
    tags: ["Investment", "Equities", "Indian Market", "Research"],
    type: "Full–time",
  },
  {
    title: "Indian Pakistani Chef",
    company: "Infusion Village Restaurant",
    location: "London",
    country: "UK",
    city: "London",
    domain: "Hospitality",
    experience: "Mid career",
    minExperience: 2,
    time: "Recent",
    tags: ["Cooking", "Indian Cuisine", "Pakistani Cuisine"],
    type: "Full–time",
  },
  {
    title: "Sales Development Representative (Outbound)",
    company: "Kovai.co",
    location: "London",
    country: "UK",
    city: "London",
    domain: "Sales",
    experience: "Entry level",
    minExperience: 1,
    time: "Recent",
    tags: ["Sales", "Outbound", "B2B", "Software"],
    type: "Full–time",
  },
  {
    title: "Student Registry and Program Coordinator",
    company: "Sommet Education",
    location: "London",
    country: "UK",
    city: "London",
    domain: "Education",
    experience: "Mid career",
    minExperience: 2,
    time: "Recent",
    tags: ["Academic Admin", "Higher Education", "Registry"],
    type: "Full–time",
  },
  {
    title: "Senior Customer Experience Manager",
    company: "Vaibhav Global",
    location: "London",
    country: "UK",
    city: "London",
    domain: "E-commerce",
    experience: "Senior",
    minExperience: 5,
    time: "Recent",
    tags: ["Customer Experience", "Jewelry", "Management"],
    type: "Full–time",
  },
];

const canadaJobs = [
  {
    title: "Associate",
    company: "Royal Bank of Canada",
    location: "Toronto, ON, Canada",
    country: "Canada",
    city: "Toronto",
    domain: "Banking",
    experience: "Experienced",
    minExperience: 2,
    time: "Recent",
    type: "Full–time",
    tags: ["Finance", "Client Relations"],
  },
  {
    title: "Growth Account Executive",
    company: "Toast",
    location: "Toronto, ON, Canada",
    country: "Canada",
    city: "Toronto",
    domain: "Sales",
    experience: "Experienced",
    minExperience: 3,
    time: "Recent",
    type: "Full–time",
    tags: ["B2B", "SaaS", "Salesforce"],
  },
  {
    title: "Food Service Manager, CSNM (Healthcare)",
    company: "Compass Group",
    location: "Toronto, Canada",
    country: "Canada",
    city: "Toronto",
    domain: "Healthcare",
    experience: "Experienced",
    minExperience: 5,
    time: "Recent",
    type: "Full–time",
    tags: ["Healthcare", "Food Safety"],
  },
  {
    title: "Regional Operations Manager - Canada",
    company: "GUCCI / Kering",
    location: "Toronto, ON, Canada",
    country: "Canada",
    city: "Toronto",
    domain: "Luxury Retail",
    experience: "Experienced",
    minExperience: 6,
    time: "Recent",
    type: "Full–time",
    tags: ["Retail Ops", "Luxury", "Leadership"],
  },
  {
    title: "Openshift Administrator",
    company: "Randstad Canada",
    location: "Toronto, ON, Canada",
    country: "Canada",
    city: "Toronto",
    domain: "IT",
    experience: "Experienced",
    minExperience: 4,
    time: "Recent",
    type: "Contractor",
    tags: ["DevOps", "Kubernetes", "OpenShift"],
  },
  {
    title: "Associate Manager, Enterprise Solutions Specialist",
    company: "PepsiCo",
    location: "Toronto, ON, Canada",
    country: "Canada",
    city: "Toronto",
    domain: "FMCG",
    experience: "Experienced",
    minExperience: 5,
    time: "Recent",
    type: "Full–time",
    tags: ["Enterprise Solutions", "Team Lead"],
  },
  {
    title: "Branch Manager - Retail (Pending LMIA)",
    company: "A to Z Optical Inc.",
    location: "Toronto, MB, Canada",
    country: "Canada",
    city: "Toronto",
    domain: "Retail",
    experience: "Experienced",
    minExperience: 3,
    time: "Recent",
    type: "Full–time",
    tags: ["Retail Sales", "Store Management"],
  },
  {
    title: "Retail Inventory Team Lead",
    company: "New Balance",
    location: "Toronto, ON, Canada",
    country: "Canada",
    city: "Toronto",
    domain: "Retail",
    experience: "Experienced",
    minExperience: 2,
    time: "Recent",
    type: "Full–time",
    tags: ["Inventory", "Retail Ops"],
  },
];
const germanyJobs = [
  {
    title: "Regional Sales Manager - General Trade",
    company: "Foresight Management Consultants",
    location: "Berlin",
    country: "Germany",
    city: "Berlin",
    domain: "Sales",
    experience: "Senior",
    minExperience: 6,
    time: "Recent",
    tags: [
      "General Trade",
      "Distribution Management",
      "Market Penetration",
      "Team Management",
      "Market Development"
    ],
  },
  {
    title: "Logistics, Operations & SCM Manager",
    company: "Abroad Pathway Immigration Consultant",
    location: "Berlin",
    country: "Germany",
    city: "Berlin",
    domain: "Supply Chain",
    experience: "Mid career",
    minExperience: 4,
    time: "Recent",
    tags: [
      "Supply Chain Management",
      "Inventory Management",
      "Logistics",
      "Procurement",
      "Transport Management"
    ],
  },
  {
    title: "Operating Room Assistant (OTA)",
    company: "AMM India",
    location: "Berlin",
    country: "Germany",
    city: "Berlin",
    domain: "Healthcare",
    experience: "Mid career",
    minExperience: 2,
    time: "Recent",
    tags: ["Nursing", "OTA", "Room Assistance", "Surgical", "Healthcare"],
  },
  {
    title: "Production Manager",
    company: "Ramkripa International",
    location: "Berlin",
    country: "Germany",
    city: "Berlin",
    domain: "Manufacturing",
    experience: "Senior",
    minExperience: 7,
    time: "Recent",
    tags: [
      "Production Management",
      "Furnace Maintenance",
      "Refining",
      "Quality Control",
      "Operations"
    ],
  },
  {
    title: "Automobile Mechanic (Car / Bus / Truck)",
    company: "Multibhashi",
    location: "Berlin",
    country: "Germany",
    city: "Berlin",
    domain: "Automobile",
    experience: "Senior",
    minExperience: 8,
    time: "Recent",
    tags: ["Mechanic", "Repairs", "Vehicles", "Bus", "Truck", "Workshop"],
  },
  {
    title: "Software Engineer",
    company: "Abroad Pathway Immigration Consultant",
    location: "Berlin",
    country: "Germany",
    city: "Berlin",
    domain: "IT",
    experience: "Mid career",
    minExperience: 3,
    time: "Recent",
    tags: ["Java", "Python", "Web Development", "Software Engineering"],
  },
  {
    title: "Electrical Service Engineer",
    company: "Ridhi Consulting Services",
    location: "Berlin",
    country: "Germany",
    city: "Berlin",
    domain: "Electrical",
    experience: "Mid career",
    minExperience: 5,
    time: "Recent",
    tags: ["PLC", "Automation", "Motors", "Installation", "Drives"],
  },
  {
    title: "ICU/OT/Ward Nurse",
    company: "Hospitals in Germany",
    location: "Berlin",
    country: "Germany",
    city: "Berlin",
    domain: "Healthcare",
    experience: "Entry level",
    minExperience: 1,
    time: "Recent",
    tags: ["Nurse", "ICU", "Ward", "OT", "CTVS", "Healthcare"],
  },
  {
    title: "AC Technician",
    company: "Multibhashi",
    location: "Berlin",
    country: "Germany",
    city: "Berlin",
    domain: "HVAC",
    experience: "Junior",
    minExperience: 1,
    time: "Recent",
    tags: ["AC Maintenance", "Installation", "Repairs"],
  },
  {
    title: "Process Safety Manager",
    company: "Apex Career Consultants",
    location: "Berlin",
    country: "Germany",
    city: "Berlin",
    domain: "Industrial Safety",
    experience: "Senior",
    minExperience: 10,
    time: "Recent",
    tags: ["HAZOP", "PSM", "Risk Analysis", "Process Safety"],
  },
  {
    title: "Business Development Manager - Europe",
    company: "Sharda Motor",
    location: "Berlin",
    country: "Germany",
    city: "Berlin",
    domain: "Business Development",
    experience: "Senior",
    minExperience: 5,
    time: "Recent",
    tags: [
      "B2B Sales",
      "Aftermarket",
      "Automotive Sales",
      "Channel Development"
    ],
  },
  
];
const australiaJobs = [
  {
    title: "Software Tester",
    company: "AI Talent",
    location: "Melbourne",
    country: "Australia",
    city: "Melbourne",
    domain: "IT & Software Testing",
    experience: "Mid-level",
    minExperience: 3,
    time: "Recent",
    tags: ["Testing", "Automation", "Manual", "QA"]
  },
  {
    title: "Software Tester",
    company: "IVEGA Group Pty Ltd",
    location: "Melbourne",
    country: "Australia",
    city: "Melbourne",
    domain: "IT & Software Development",
    experience: "Mid-level",
    minExperience: 3,
    time: "Recent",
    tags: ["Java", "Selenium", "Agile", "Test Cases"]
  },
  {
    title: "Pressure Welder",
    company: "A & G Engineering",
    location: "Melbourne",
    country: "Australia",
    city: "Melbourne",
    domain: "Manufacturing & Engineering",
    experience: "Experienced",
    minExperience: 5,
    time: "Recent",
    tags: ["Welding", "Stainless Steel", "Pressure Equipment"]
  },
  {
    title: "Motor Mechanic",
    company: "MCJ Automotive (Rapid Tune)",
    location: "Melbourne",
    country: "Australia",
    city: "Melbourne",
    domain: "Automotive",
    experience: "Experienced",
    minExperience: 4,
    time: "Recent",
    tags: ["Mechanic", "Vehicle Repair", "Engine Service"]
  },
  {
    title: "ICT Sales Representative",
    company: "Philip Riley",
    location: "Melbourne",
    country: "Australia",
    city: "Melbourne",
    domain: "ICT Sales",
    experience: "Mid-level",
    minExperience: 3,
    time: "Recent",
    tags: ["B2B", "Tech Sales", "Client Acquisition"]
  },
  {
    title: "Registered Nurse - Aged Care",
    company: "HealthStaff Recruitment",
    location: "Melbourne",
    country: "Australia",
    city: "Melbourne",
    domain: "Healthcare",
    experience: "Entry level",
    minExperience: 1,
    time: "Recent",
    tags: ["Nursing", "Aged Care", "Patient Care"]
  },
  {
    title: "HVAC Technician",
    company: "Aircon Australia",
    location: "Melbourne",
    country: "Australia",
    city: "Melbourne",
    domain: "HVAC",
    experience: "Junior",
    minExperience: 2,
    time: "Recent",
    tags: ["Air Conditioning", "Maintenance", "Repairs", "Ducting"]
  }
];

const luxembourgJobs = [
  {
    title: "Full Stack Developer",
    company: "LuxTech Solutions",
    location: "Luxembourg City",
    country: "Luxembourg",
    city: "Luxembourg City",
    domain: "IT & Software Development",
    experience: "Mid-level",
    minExperience: 3,
    time: "Recent",
    tags: ["JavaScript", "Node.js", "React", "MySQL"]
  },
  {
    title: "Mechanical Design Engineer",
    company: "Innovent Engineering",
    location: "Luxembourg City",
    country: "Luxembourg",
    city: "Luxembourg City",
    domain: "Mechanical Engineering",
    experience: "Experienced",
    minExperience: 5,
    time: "Recent",
    tags: ["CAD", "SolidWorks", "Prototyping", "Manufacturing"]
  },
  {
    title: "Financial Analyst",
    company: "EuroBank Capital",
    location: "Luxembourg City",
    country: "Luxembourg",
    city: "Luxembourg City",
    domain: "Finance & Banking",
    experience: "Mid-level",
    minExperience: 4,
    time: "Recent",
    tags: ["Excel", "Budgeting", "Reporting", "Forecasting"]
  },
  {
    title: "Registered Nurse",
    company: "LuxCare Hospitals",
    location: "Luxembourg City",
    country: "Luxembourg",
    city: "Luxembourg City",
    domain: "Healthcare",
    experience: "Entry level",
    minExperience: 1,
    time: "Recent",
    tags: ["Nursing", "ICU", "Patient Care", "Hospital"]
  },
  {
    title: "Business Development Manager",
    company: "NextGen Trade Co.",
    location: "Luxembourg City",
    country: "Luxembourg",
    city: "Luxembourg City",
    domain: "Sales & Business Development",
    experience: "Senior",
    minExperience: 7,
    time: "Recent",
    tags: ["B2B", "Sales Strategy", "Client Acquisition"]
  },
  {
    title: "Electrical Technician",
    company: "VoltWorks Ltd.",
    location: "Luxembourg City",
    country: "Luxembourg",
    city: "Luxembourg City",
    domain: "Electrical Engineering",
    experience: "Junior",
    minExperience: 2,
    time: "Recent",
    tags: ["Circuits", "Wiring", "Installations", "Maintenance"]
  },
  {
    title: "Data Analyst",
    company: "InsightX Analytics",
    location: "Luxembourg City",
    country: "Luxembourg",
    city: "Luxembourg City",
    domain: "Data & Analytics",
    experience: "Mid-level",
    minExperience: 3,
    time: "Recent",
    tags: ["SQL", "Python", "Data Visualization", "Power BI"]
  },
  {
    title: "HVAC Engineer",
    company: "ClimaLux Services",
    location: "Luxembourg City",
    country: "Luxembourg",
    city: "Luxembourg City",
    domain: "HVAC",
    experience: "Experienced",
    minExperience: 4,
    time: "Recent",
    tags: ["HVAC", "Installation", "Cooling Systems", "Repairs"]
  }
];
const IrelandJobs = [
  {
  title: "Software Engineer",
  company: "TechBridge Ltd.",
  location: "Dublin",
  country: "Ireland",
  city: "Dublin",
  domain: "IT & Software Development",
  experience: "Mid career",
  minExperience: 3,
  time: "Recent",
  tags: ["React", "Node.js", "Agile", "Microservices"]
},
{
  title: "Registered Nurse - ICU",
  company: "St. Vincent's Hospital",
  location: "Dublin",
  country: "Ireland",
  city: "Dublin",
  domain: "Healthcare",
  experience: "Entry level",
  minExperience: 1,
  time: "Recent",
  tags: ["ICU", "Patient Care", "BLS", "Critical Care"]
},
{
  title: "Mechanical Design Engineer",
  company: "GreenTech Engineering",
  location: "Dublin",
  country: "Ireland",
  city: "Dublin",
  domain: "Mechanical Engineering",
  experience: "Mid career",
  minExperience: 4,
  time: "Recent",
  tags: ["CAD", "SolidWorks", "Design", "Fabrication"]
},
{
  title: "Business Analyst",
  company: "Deloitte Ireland",
  location: "Dublin",
  country: "Ireland",
  city: "Dublin",
  domain: "Business & Consulting",
  experience: "Mid career",
  minExperience: 3,
  time: "Recent",
  tags: ["Process Mapping", "Stakeholder Management", "Agile", "UAT"]
},
{
  title: "Sales Executive - B2B",
  company: "Enterprise Solutions",
  location: "Dublin",
  country: "Ireland",
  city: "Dublin",
  domain: "Sales & Marketing",
  experience: "Junior",
  minExperience: 2,
  time: "Recent",
  tags: ["B2B", "Cold Calling", "CRM", "Salesforce"]
},
{
  title: "HVAC Maintenance Technician",
  company: "Climate Solutions",
  location: "Dublin",
  country: "Ireland",
  city: "Dublin",
  domain: "HVAC",
  experience: "Mid career",
  minExperience: 3,
  time: "Recent",
  tags: ["HVAC", "Ducting", "Ventilation", "Servicing"]
},
{
  title: "Data Analyst",
  company: "Accenture Ireland",
  location: "Dublin",
  country: "Ireland",
  city: "Dublin",
  domain: "Data & Analytics",
  experience: "Mid career",
  minExperience: 3,
  time: "Recent",
  tags: ["SQL", "Excel", "Power BI", "ETL"]
},
{
  title: "Electrician - Industrial",
  company: "PowerGrid Ireland",
  location: "Dublin",
  country: "Ireland",
  city: "Dublin",
  domain: "Electrical Engineering",
  experience: "Senior",
  minExperience: 7,
  time: "Recent",
  tags: ["Wiring", "Switchgear", "Maintenance", "Troubleshooting"]
},
{
  title: "Digital Marketing Executive",
  company: "MediaLab Ltd.",
  location: "Dublin",
  country: "Ireland",
  city: "Dublin",
  domain: "Digital Marketing",
  experience: "Junior",
  minExperience: 2,
  time: "Recent",
  tags: ["SEO", "Social Media", "Content Marketing", "Google Ads"]
}

];

const SingaporeJobs = [
{
  title: "Full Stack Developer",
  company: "Grab Holdings",
  location: "Singapore",
  country: "Singapore",
  city: "Singapore",
  domain: "IT & Software Development",
  experience: "Mid career",
  minExperience: 3,
  ttime: "Recent",
  tags: ["Node.js", "React", "MongoDB", "Agile"]
},
{
  title: "Biomedical Engineer",
  company: "National University Health System",
  location: "Singapore",
  country: "Singapore",
  city: "Singapore",
  domain: "Biomedical Engineering",
  experience: "Entry level",
  minExperience: 1,
  time: "Recent",
  tags: ["Device Testing", "R&D", "Documentation", "Clinical Trials"]
},
{
  title: "Financial Analyst",
  company: "DBS Bank",
  location: "Singapore",
  country: "Singapore",
  city: "Singapore",
  domain: "Finance & Banking",
  experience: "Mid career",
  minExperience: 3,
  time: "Recent",
  tags: ["Financial Modelling", "Excel", "Forecasting", "Budgeting"]
},
{
  title: "UX/UI Designer",
  company: "Shopee",
  location: "Singapore",
  country: "Singapore",
  city: "Singapore",
  domain: "Design & User Experience",
  experience: "Junior",
  minExperience: 2,
  time: "Recent",
  tags: ["Figma", "Prototyping", "Wireframes", "User Testing"]
},
{
  title: "Supply Chain Coordinator",
  company: "Singapore Airlines",
  location: "Singapore",
  country: "Singapore",
  city: "Singapore",
  domain: "Logistics & Supply Chain",
  experience: "Mid career",
  minExperience: 3,
  time: "Recent",
  tags: ["Inventory", "Shipping", "Procurement", "ERP"]
},
{
  title: "Cybersecurity Analyst",
  company: "GovTech Singapore",
  location: "Singapore",
  country: "Singapore",
  city: "Singapore",
  domain: "Cybersecurity",
  experience: "Mid career",
  minExperience: 4,
  time: "Recent",
  tags: ["Threat Analysis", "SIEM", "Firewall", "Incident Response"]
},
{
  title: "Urban Planner",
  company: "Urban Redevelopment Authority",
  location: "Singapore",
  country: "Singapore",
  city: "Singapore",
  domain: "Urban Development & Planning",
  experience: "Senior",
  minExperience: 6,
  time: "Recent",
  tags: ["GIS", "Zoning", "Public Policy", "Sustainability"]
},
{
  title: "Port Operations Executive",
  company: "PSA Corporation",
  location: "Singapore",
  country: "Singapore",
  city: "Singapore",
  domain: "Maritime & Port Management",
  experience: "Junior",
  minExperience: 2,
  time: "Recent",
  tags: ["Port Logistics", "Container Handling", "Safety", "Scheduling"]
},
{
  title: "AI Research Scientist",
  company: "A*STAR",
  location: "Singapore",
  country: "Singapore",
  city: "Singapore",
  domain: "Artificial Intelligence",
  experience: "Senior",
  minExperience: 5,
  time: "Recent",
  tags: ["Deep Learning", "NLP", "TensorFlow", "Model Deployment"]
}
];
const MalaysiaJobs = [
  {
  title: "Software Engineer",
  company: "AirAsia",
  location: "Kuala Lumpur",
  country: "Malaysia",
  city: "Kuala Lumpur",
  domain: "Information Technology",
  experience: "Mid career",
  minExperience: 3,
  time: "Recent",
  tags: ["Java", "Spring Boot", "REST APIs", "AWS"]
},
{
  title: "Accountant",
  company: "Petronas",
  location: "Kuala Lumpur",
  country: "Malaysia",
  city: "Kuala Lumpur",
  domain: "Finance & Accounting",
  experience: "Mid career",
  minExperience: 4,
  time: "Recent",
  tags: ["General Ledger", "Tax", "IFRS", "SAP"]
},
{
  title: "Marketing Manager",
  company: "Grab Malaysia",
  location: "Kuala Lumpur",
  country: "Malaysia",
  city: "Kuala Lumpur",
  domain: "Marketing & Advertising",
  experience: "Senior",
  minExperience: 5,
  time: "Recent",
  tags: ["Campaign Strategy", "SEO", "Digital Ads", "Brand Management"]
},
{
  title: "HR Executive",
  company: "Maybank",
  location: "Kuala Lumpur",
  country: "Malaysia",
  city: "Kuala Lumpur",
  domain: "Human Resources",
  experience: "Mid career",
  minExperience: 3,
  time: "Recent",
  tags: ["Recruitment", "Onboarding", "Payroll", "Employee Relations"]
},
{
  title: "Data Analyst",
  company: "Shopee Malaysia",
  location: "Kuala Lumpur",
  country: "Malaysia",
  city: "Kuala Lumpur",
  domain: "Data & Analytics",
  experience: "Junior",
  minExperience: 2,
  time: "Recent",
  tags: ["SQL", "Python", "Power BI", "Data Cleaning"]
},
{
  title: "Civil Engineer",
  company: "Gamuda Berhad",
  location: "Kuala Lumpur",
  country: "Malaysia",
  city: "Kuala Lumpur",
  domain: "Construction & Engineering",
  experience: "Senior",
  minExperience: 6,
  time: "Recent",
  tags: ["AutoCAD", "Project Planning", "Site Supervision", "Structural Design"]
},
{
  title: "Customer Service Officer",
  company: "Telekom Malaysia",
  location: "Kuala Lumpur",
  country: "Malaysia",
  city: "Kuala Lumpur",
  domain: "Customer Service",
  experience: "Entry level",
  minExperience: 1,
  time: "Recent",
  tags: ["CRM", "Problem Solving", "Communication", "Call Handling"]
},
{
  title: "Graphic Designer",
  company: "Astro Malaysia",
  location: "Kuala Lumpur",
  country: "Malaysia",
  city: "Kuala Lumpur",
  domain: "Creative Design",
  experience: "Mid career",
  minExperience: 3,
  time: "Recent",
  tags: ["Adobe Photoshop", "Illustrator", "Branding", "UI Assets"]
},
{
  title: "Cybersecurity Engineer",
  company: "Fusionex",
  location: "Kuala Lumpur",
  country: "Malaysia",
  city: "Kuala Lumpur",
  domain: "Cybersecurity",
  experience: "Mid career",
  minExperience: 4,
  time: "Recent",
  tags: ["Pen Testing", "SIEM", "Network Security", "Compliance"]
},
{
  title: "Logistics Coordinator",
  company: "DHL Malaysia",
  location: "Kuala Lumpur",
  country: "Malaysia",
  city: "Kuala Lumpur",
  domain: "Logistics & Supply Chain",
  experience: "Mid career",
  minExperience: 3,
  time: "Recent",
  tags: ["Warehouse", "Shipping", "Freight", "Inventory Management"]
}
];
const DenmarkJobs = [
{
  title: "Frontend Developer",
  company: "Unity Technologies",
  location: "Copenhagen",
  country: "Denmark",
  city: "Copenhagen",
  domain: "Information Technology",
  experience: "Mid career",
  minExperience: 3,
  time: "Recent",
  tags: ["React", "JavaScript", "UI/UX", "HTML/CSS"]
},
{
  title: "Wind Energy Engineer",
  company: "Vestas Wind Systems",
  location: "Copenhagen",
  country: "Denmark",
  city: "Copenhagen",
  domain: "Renewable Energy",
  experience: "Senior",
  minExperience: 5,
  time: "Recent",
  tags: ["Turbines", "Wind Farms", "CAD", "Energy Efficiency"]
},
{
  title: "Pharmaceutical Scientist",
  company: "Novo Nordisk",
  location: "Copenhagen",
  country: "Denmark",
  city: "Copenhagen",
  domain: "Pharmaceuticals",
  experience: "Mid career",
  minExperience: 4,
  time: "Recent",
  tags: ["Drug Development", "GMP", "Clinical Trials", "R&D"]
},
{
  title: "UX Designer",
  company: "Bang & Olufsen",
  location: "Copenhagen",
  country: "Denmark",
  city: "Copenhagen",
  domain: "Product Design",
  experience: "Mid career",
  minExperience: 3,
  time: "Recent",
  tags: ["User Research", "Figma", "Prototyping", "Human-Centered Design"]
},
{
  title: "Software Engineer – Robotics",
  company: "Universal Robots",
  location: "Copenhagen",
  country: "Denmark",
  city: "Copenhagen",
  domain: "Robotics & Automation",
  experience: "Senior",
  minExperience: 5,
  time: "Recent",
  tags: ["Python", "ROS", "Embedded Systems", "Sensors"]
},
{
  title: "Marine Engineer",
  company: "Maersk",
  location: "Copenhagen",
  country: "Denmark",
  city: "Copenhagen",
  domain: "Shipping & Maritime",
  experience: "Mid career",
  minExperience: 4,
  time: "Recent",
  tags: ["Naval Architecture", "Logistics", "Shipbuilding", "Maritime Regulations"]
},
{
  title: "Clinical Data Analyst",
  company: "Lundbeck",
  location: "Copenhagen",
  country: "Denmark",
  city: "Copenhagen",
  domain: "Life Sciences",
  experience: "Mid career",
  minExperience: 3,
  time: "Recent",
  tags: ["SAS", "Data Analysis", "Clinical Trials", "GCP"]
},
{
  title: "Supply Chain Manager",
  company: "Carlsberg Group",
  location: "Copenhagen",
  country: "Denmark",
  city: "Copenhagen",
  domain: "Supply Chain & Logistics",
  experience: "Mid career",
  minExperience: 4,
  time: "Recent",
  tags: ["Procurement", "SAP", "Inventory", "Distribution"]
},
{
  title: "DevOps Engineer",
  company: "Trustpilot",
  location: "Copenhagen",
  country: "Denmark",
  city: "Copenhagen",
  domain: "Cloud & DevOps",
  experience: "Mid career",
  minExperience: 3,
  time: "Recent",
  tags: ["CI/CD", "Docker", "AWS", "Kubernetes"]
},
{
  title: "Biomedical Engineer",
  company: "Coloplast",
  location: "Copenhagen",
  country: "Denmark",
  city: "Copenhagen",
  domain: "Healthcare Technology",
  experience: "Mid career",
  minExperience: 3,
  time: "Recent",
  tags: ["Medical Devices", "Product Testing", "ISO Standards", "Regulatory Affairs"]
}


];
const SouthafricaJobs = [

{
  title: "Software Developer",
  company: "MTN Group",
  location: "Johannesburg",
  country: "Southafrica",
  city: "Johannesburg",
  domain: "Information Technology",
  experience: "Mid career",
  minExperience: 3,
  time: "Recent",
  tags: ["JavaScript", "React", "Node.js", "REST APIs"]
},
{
  title: "Mining Engineer",
  company: "Anglo American",
  location: "Johannesburg",
  country: "Southafrica",
  city: "Johannesburg",
  domain: "Mining & Engineering",
  experience: "Senior",
  minExperience: 5,
  time: "Recent",
  tags: ["Open Pit", "Underground", "Safety", "AutoCAD"]
},
{
  title: "Financial Analyst",
  company: "Standard Bank",
  location: "Johannesburg",
  country: "Southafrica",
  city: "Johannesburg",
  domain: "Finance & Banking",
  experience: "Mid career",
  minExperience: 4,
  time: "Recent",
  tags: ["Forecasting", "Excel", "Reporting", "Risk Analysis"]
},
{
  title: "Nurse Practitioner",
  company: "Netcare Hospitals",
  location: "Johannesburg",
  country: "Southafrica",
  city: "Johannesburg",
  domain: "Healthcare & Nursing",
  experience: "Mid career",
  minExperience: 3,
  time: "Recent",
  tags: ["Patient Care", "ICU", "Ward Management", "Medical Records"]
},
{
  title: "Electrical Engineer",
  company: "Eskom Holdings",
  location: "Johannesburg",
  country: "Southafrica",
  city: "Johannesburg",
  domain: "Energy & Utilities",
  experience: "Senior",
  minExperience: 5,
  time: "Recent",
  tags: ["Power Systems", "Substations", "Load Forecasting", "SCADA"]
},
{
  title: "Marketing Specialist",
  company: "Nando's South Africa",
  location: "Johannesburg",
  country: "Southafrica",
  city: "Johannesburg",
  domain: "Marketing & Branding",
  experience: "Mid career",
  minExperience: 4,
  time: "Recent",
  tags: ["Content Creation", "Brand Strategy", "Social Media", "Campaigns"]
},
{
  title: "Call Center Agent",
  company: "Vodacom",
  location: "Johannesburg",
  country: "Southafrica",
  city: "Johannesburg",
  domain: "Customer Support",
  experience: "Entry level",
  minExperience: 1,
  time: "Recent",
  tags: ["CRM", "Inbound Calls", "Customer Queries", "Communication"]
},
{
  title: "Civil Engineer",
  company: "Murray & Roberts",
  location: "Johannesburg",
  country: "Southafrica",
  city: "Johannesburg",
  domain: "Infrastructure & Construction",
  experience: "Mid career",
  minExperience: 3,
  time: "Recent",
  tags: ["Site Planning", "Project Supervision", "CAD", "Piling"]
},
{
  title: "Cybersecurity Analyst",
  company: "Dimension Data",
  location: "Johannesburg",
  country: "Southafrica",
  city: "Johannesburg",
  domain: "Cybersecurity",
  experience: "Mid career",
  minExperience: 4,
  time: "Recent",
  tags: ["Firewall", "Threat Detection", "SIEM", "Incident Response"]
},
{
  title: "Supply Chain Coordinator",
  company: "Shoprite Holdings",
  location: "Johannesburg",
  country: "Southafrica",
  city: "Johannesburg",
  domain: "Logistics & Supply Chain",
  experience: "Mid career",
  minExperience: 3,
  time: "Recent",
  tags: ["Inventory", "Freight", "Distribution", "Procurement"]
}


];

const jobData = [...uaeDubaiJobs, ...londonJobs, ...canadaJobs, ...germanyJobs, ...australiaJobs, ...luxembourgJobs, ...IrelandJobs, ...SingaporeJobs, ...MalaysiaJobs, ...SouthafricaJobs, ...DenmarkJobs, ];

export default jobData;
